### PR TITLE
Portability improvements, cleanup, and bug fixes

### LINKED ISSUE #25: Compilation failure on OpenBSD
FWIW, this (#23 and #22) breaks on OpenBSD.  Mostly due to the fact that -lresolv doesn't exist there (nor on some other BSDs), normally these days the libresolv stuff is provided directly by libc both on BSDs and GNU systems but OS X seems to not have followed suite?  Dynamically adding -lresolv to the linker line is slightly tricky to do in some form of portable Make -- since everyone wants to be special.

_Originally posted by @ams in https://github.com/PDP-10/supdup/pull/23#issuecomment-698755348_

### LINKED ISSUE #35: Maybe necessary to link with tinfo?
@ams and @drforbin, please continue discussion here.  I'm curious why -ltinfo would be needed now, when it was not the case before.  Please elaborate.

See also: https://github.com/PDP-10/its/issues/2322

### LINKED ISSUE #38: Create a README.md
We should probably create a `README.md` that:
* describes the program,
* links to relevant RFC documentation,
* documents both build requirements (*i.e.* `ncurses`) and,
  * optional (but recommended) dependencies (*i.e.* `pkg-config`),
* documents supported and tested operating systems and compilers,
* provides bug reporting instructions for end-users.

### PR DESCRIPTION
**Pull request by johnsonjh**
* Portability improvements, cleanup, and bug fixes:
  * Add or fix support for building on Solaris, illumos, Linux/musl, NetBSD, OpenBSD, IBM AIX, IBM OS/400 (PASE), Cygwin, and Haiku, which weren't previously cleanly building.
  * Use `pkg-config` when available to determine CFLAGS and libraries.
  * Initialize some variables in `supdupd`.
  * Fix off-by-one error in `supdup`.
  * Suppress spurious error when Chaosnet bridge socket is missing.
  * Create `README.md`.
  * Cleanup Makefile.
  * Properly detect bad ports (negative or >65535).
  * Fix non-ANSI function declarations.
  * Add `*.ln` (*Lint*) files, `supdupd`, and `compile_commands.json` to `.gitignore`.
  * Create `.gitattributes`.
  * Ensure file handle is valid (non-negative) before closing.
  * Correct various spelling errors.
[]()

[]()
  * Tested build under Oracle Solaris, OpenIndiana illumos, Linux/musl, Linux/glibc, IBM AIX, IBM OS/400 (PASE), Haiku, FreeBSD, OpenBSD, NetBSD, DragonFly BSD, Cygwin, and Apple macOS.

  * Compilation tested and working with PCC, GCC, Clang, Xcode, IBM XL C, IBM Open XL C, Oracle Studio C, NVIDIA HPC SDK C, Portland Group C, and DMD ImportC.

  * Passes Cppcheck and Clang Analyzer.
[]()

[]()
  * Resolves GitHub Issues:
    * Closes #25 
    * Closes #35
    * Closes #38

Signed-off-by: Jeffrey H. Johnson \<trnsz@pobox.com\>

### CODE REVIEW

File: GNUmakefile [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+SHELL = /bin/sh
+PREFIX ?= /usr/local
+
+OS_NAME = $(shell uname)
+
+CC ?= cc
+CFLAGS += $(shell pkg-config --cflags ncurses 2> /dev/null) -g -Wall
+LDFLAGS += -g
+
+# AIX needs linking libcurses *after* libncurses
```
Comment (ams) [inline GNUmakefile]: Why does AIX need both curses _and _ ncurses?

File: GNUmakefile [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+ifeq ($(OS_NAME), AIX)
+ EXTRA_LDFLAGS = -lcurses
+endif
+
+# Mac OSX
+ifeq ($(OS_NAME), Darwin)
+ LDFLAGS = -L/opt/local/lib
```
Comment (ams) [inline GNUmakefile]: Doesn't this assume Macports?  Does it still work if one uses Homebrew?

File: GNUmakefile [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+ CFLAGS += -I/usr/pkg/include -I/usr/pkg/include/ncurses
+ LDFLAGS += -L/usr/pkg/lib
+endif
+
+# The server isn't ready for prime time.
+all:	supdup
+
+SUPDUP_OBJS = supdup.o charmap.o tcp.o chaos.o
+supdup: $(SUPDUP_OBJS)
+	$(CC) $(LDFLAGS) -o $@ $(SUPDUP_OBJS) $(shell pkg-config --libs ncurses 2> /dev/null || printf '%s' "-lncurses") $(EXTRA_LDFLAGS)
```
Comment (ams) [inline GNUmakefile]: Yuck .. but maybe put this `$(shell peg-config ...)` stuff into a variable, and then use it... With a small comment on why this ugly stuff. :-)

File: chaos.c [hunk 4]
```diff
@@ -4,33 +4,38 @@
 
 #if USE_CHAOS_STREAM_SOCKET
 
-#include <stdio.h>
```
Comment (ams) [inline chaos.c]: Seems this is a but superfluous?  I have no opinion though ..

File: supdup.c [hunk 5]
```diff
@@ -164,7 +165,11 @@ struct	sgttyb ottyb;
 unsigned int sup_ispeed = 9600, sup_ospeed = 9600;
 #else
 struct termios otio;
+# ifndef __HAIKU__
 speed_t sup_ispeed = 9600, sup_ospeed = 9600;
+# else
+unsigned int sup_ispeed = 9600, sup_ospeed = 9600;
+# endif
```
Comment (ams) [inline supdup.c]: What about making a typedef for speed_t if and only if __HAIKU__?

Comment (larsbrinkhoff) [reply supdup.c]: I think that's a good suggestion.

File: chaos.c [hunk 6]
```diff
@@ -9,7 +9,7 @@
 #include <unistd.h>
 #include <string.h>
 #include <sys/un.h>
-#if defined(__HAIKU__) || defined(__OpenBSD__)|| defined(__NetBSD__)
```
Comment (larsbrinkhoff) [inline chaos.c]: I'd like the pull request to be refactored a bit so that changes like this that revise previous changes, are folded back into those commits.

Comment (larsbrinkhoff) [reply chaos.c]: This commit is the most obvious one, but there are bits and pieces here and there that also apply.

File: chaos.c [hunk 7]
```diff
@@ -9,7 +9,7 @@
 #include <unistd.h>
 #include <string.h>
 #include <sys/un.h>
-#ifdef __HAIKU__
+#if defined(__HAIKU__) || defined(__OpenBSD__)
```
Comment (larsbrinkhoff) [inline chaos.c]: I appreciate leaving old code alone, but in this case I think we should go out on a limb and always use <errno.h>.

File: GNUmakefile (hunk 1 above)
Comment (johnsonjh) [reply GNUmakefile]: I wish I knew.  It could probably be made to work with AIX xcurses (in base) rather than ncurses, but ncurses is an available package.

File: GNUmakefile (hunk 2 above)
Comment (johnsonjh) [reply GNUmakefile]: That came from the original Makefile... I don't have MacPorts installed and it worked fine for me in testing.

File: chaos.c (hunk 7 above)
Comment (johnsonjh) [reply chaos.c]: I will do that later today when I push an update.

File: chaos.c (hunk 4 above)
Comment (johnsonjh) [reply chaos.c]: Yeah, that's just GNU style (modifications via GNU Cppi tool).  If you hate it, I can revert.

File: GNUmakefile (hunk 3 above)
Comment (johnsonjh) [reply GNUmakefile]: Will do

File: supdup.c (hunk 5 above)
Comment (johnsonjh) [reply supdup.c]: I'm not familiar with speed_t but on Haiku, it is a signed char or something like that, so it gets set to 128, which doesn't seem to be what is intended.

@ams @larsbrinkhoff is there any problem using unsigned int everywhere?  I can also do a typedef or definition of course.

File: chaos.c (hunk 6 above)
Comment (johnsonjh) [reply chaos.c]: Later OS support is all kind of intertwined at this point now, so I'll probably just squash it down into one commit without cosmetic changes.

File: supdup.c (hunk 5 above)
Comment (johnsonjh) [reply supdup.c]: I'll have do a define, seems speed_t is a basic type on Haiku

**Comment by johnsonjh** [comment]
@ams 

About AIX, XCurses (Extended Curses, in AIX 7 base) does work, and can be built as follows with this PR applied and including "curses.h" instead of "ncurses.h" in supdup.c:

```
$ env CC="gcc-12" gmake NCURSES_LIBS="-lxcurses" EXTRA_LDFLAGS=" "
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o supdup.o supdup.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o charmap.o charmap.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o tcp.o tcp.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o chaos.o chaos.c
gcc-12 -g -o supdup supdup.o charmap.o tcp.o chaos.o -lxcurses
```

To answer your earlier question about why libcurses is required when using ncurses:

```
jhj@force ~/src/supdup $ env CC="gcc-12" gmake EXTRA_LDFLAGS=" "
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o supdup.o supdup.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o charmap.o charmap.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o tcp.o tcp.c
gcc-12 -D_ALL_SOURCE -I/opt/freeware/include -g -Wall   -c -o chaos.o chaos.c
gcc-12 -g -o supdup supdup.o charmap.o tcp.o chaos.o -L/opt/freeware/lib64 -lncurses
ld: 0711-317 ERROR: Undefined symbol: cur_term
ld: 0711-317 ERROR: Undefined symbol: .tputs
ld: 0711-317 ERROR: Undefined symbol: .setupterm
ld: 0711-317 ERROR: Undefined symbol: .tparm
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
gmake: *** [GNUmakefile:44: supdup] Error 1
```

I still think we should require ncurses on AIX.  We use ncurses on every other platform, and ncurses is usually integrated with pkg-config so it's easier to get the proper cflags and ldflags automatically.

Adding more complexity in the makefile to avoid requiring ncurses to be installed on AIX isn't a great tradeoff since ncurses is packaged by IBM, and if it's installed, everything works on AIX with a simple "gmake".  If ncurses isn't installed, the error is also obvious.

Everything is also working with IBM's proprietary compilers in the latest commit, both 32- and 64-bit:

IMG_1386

I've actually tested both V16 (XL) and V17 (Open XL) successfully.

**Comment by johnsonjh** [comment]
Also, I'm going to drop defaulting `-g -Wall`.  If users want that they can easily adjust the CFLAGS, and it will unbreak building with proprietary compilers like Oracle Studio and IBM XL C, that don't use GNU compatible command invocations.

Squashing.

**Comment by johnsonjh** [comment]
[Moved to GitHub Issue #39.]

File: supdup.c (hunk 5 above)
Comment (ams) [reply supdup.c]: Oh, so there is a speet_t on Haiku, but it is signed char instead of unsigned int? That seems annoying.

Comment (johnsonjh) [reply supdup.c]: Yes. :(

File: chaos.c (hunk 4 above)
Comment (larsbrinkhoff) [reply chaos.c]: I don't see that this was resolved in the discussions.  I think minor whitespace cleanup is ok, but major reformatting is not.

Comment (johnsonjh) [reply chaos.c]: That change is from [GNU Cppi](https://www.gnu.org/software/cppi/) which normalizes preprocessor indentation to GNU style - it's indenting by one space because those preprocessor directives are inside the conditional #if block.

Comment (larsbrinkhoff) [reply chaos.c]: Sure, but we haven't adopted GNU style here.  At least it hasn't been discussed and agreed on.

Comment (johnsonjh) [reply chaos.c]: I can revert to the previous flat style with no indentation (all preprocessor directives left justified) if it's preferred.  I apologize, it's something that I (and my default editor configuration) do automatically.

Comment (larsbrinkhoff) [reply chaos.c]: Oh no, need to apologize!  We have these reviews and discussions to hash things out.

In my view, reformatting be more nuisance than it's worth.  Say, if someone patched a fork and wanted to apply it here later.  It's also polite to adopt the existing code style.  So that's my preference, but I'm not saying I have the final say.

Comment (johnsonjh) [reply chaos.c]: OK, I'll still lean to the new formatting due to the (IMO, massive) readability improvements, but let me know either way.

Comment (ams) [reply chaos.c]: I'm with @larsbrinkhoff -- one benefit of keeping formatting is that when you compare to old versions of supdup that might surface it is much much easier to find changes.

As for GNU cppi .. I personally find it ugly, and it isn't that commonly adopted in GNU.

**Comment by bscottm** [comment]
@larsbrinkhoff: Is this going to get integrated?

**Comment by larsbrinkhoff** [comment]
@bscottm, I think so, but there was some discussion and I'm not sure everything was resolved.  I'll take a look now.

File: GNUmakefile [hunk 8]
```diff
@@ -0,0 +1,71 @@
+# Makefile for the supdup server and client.
```
Comment (larsbrinkhoff) [inline GNUmakefile]: Please keep the old file name.

File: chaos.c (hunk 4 above)
Comment (larsbrinkhoff) [reply chaos.c]: Please undo the reformatting.

File: supdup.c [hunk 9]
```diff
@@ -30,11 +30,11 @@
  *  Try multiple other host addresses if first fails.
  */
 
-#ifndef USE_TERMIOS
```
Comment (larsbrinkhoff) [inline supdup.c:33]: Please keep the ifndef.

File: supdup.c [hunk 10]
```diff
@@ -474,7 +484,7 @@ static signed char inits[] =
     // UNAME
     0,	0,	0,	0,	0,	0
   };
-#define	INIT_LEN	(sizeof(inits)) // 42	/* Number of bytes to send at initialization */
```
Comment (larsbrinkhoff) [inline supdup.c]: Please undo this whitespace change.

File: supdup.c [hunk 11]
```diff
@@ -524,7 +534,7 @@ sup_term (void)
  *    exit (1);
  *  }
  */
-
```
Comment (larsbrinkhoff) [inline supdup.c]: I think this whitespace cleanup is ok, but it should be in a separate commit.  Not mixed in with functional changes.

File: supdup.c [hunk 12]
```diff
@@ -1218,16 +1236,16 @@ rlogout (void)
 /*
  * Supdup receiver states for fsm
  */
-#define	SR_DATA		0
```
Comment (larsbrinkhoff) [inline supdup.c]: This type of whitespace change doesn't buy much.

File: supdupd.c [hunk 13]
```diff
@@ -52,18 +62,18 @@
 #include <sgtty.h>
 #include <netdb.h>
 
-#ifdef TERMINFO
```
Comment (larsbrinkhoff) [inline supdupd.c]: Keep ifdef throughout the pull request.  Changing it to if defined() doesn't buy much.

File: README.md [hunk 14]
```diff
@@ -1 +1,93 @@
...
+
+## Overview
+
+* `supdup` is a client (and `supdupd` is a server) implementing the SUPDUP (*Sup*er *Dup*er TELNET) protocol, a highly efficient [TELNET](https://www.rfc-editor.org/rfc/rfc854.txt)-style remote display protocol, on UNIX-like systems.
+
+* It originated as a private protocol between the [Chaosnet](https://chaosnet.net/)-connected ITS systems at MIT to allow a user at any one of these systems to use one of the others as a display; later implementations were developed for [various platforms](https://gunkies.org/wiki/Chaosnet#Protocol_implementations).
+
+* The software supports connections over TCP/IP and Chaosnet (optionally using the [cbridge](https://github.com/bictorv/chaosnet-bridge) software).
+
+## Supported platforms
```
Comment (larsbrinkhoff) [inline README.md]: We don't _support_ anything, really.  Please rephrase.

**Review by larsbrinkhoff — CHANGES_REQUESTED** [review]
I left some comments about things that I'd like to see changed.

**Comment by johnsonjh** [comment]
> I left some comments about things that I'd like to see changed.

I'll get to this in the next day or two!

File: GNUmakefile (hunk 8 above)
Comment (johnsonjh) [reply GNUmakefile]: Any reason why?

The Makefile does (and did before my changes as well) require GNU Make, which always looks for GNUmakefile first, and falls back to Makefile or makefile for compatibility.

Leaving it as is works, but you'll a lot of unhelpful error messages trying to build with the default make of Solaris or the BSDs without any indication that GNU Make is required (without reading the README, I guess).

Comment (ams) [reply GNUmakefile]: You'll get a similar unhelpful error message even if you rename it to GNUmakefile, or worse do "make supdup" it will try to compile supdup anyway, and most likely bail hard.

Comment (johnsonjh) [reply GNUmakefile]: Well, “`no target to make`”, IMO, is better than:
```sh
make: "/home/jhj/src/supdup/Makefile" line 14: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 16: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 19: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 21: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 24: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 27: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 30: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 32: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 35: Invalid line type
make: "/home/jhj/src/supdup/Makefile" line 38: Invalid line type
make: Fatal errors encountered -- cannot continue
```

I could also add a POSIX/BSD-compatible Makefile that attempts to invoke `gmake` if it is available in the PATH, and provide a friendlier error if not.

If you prefer leaving it as-is, that’s fine I guess, just my OCD gets triggered having it named like it is a (POSIX) Makefile, when it is really a GNUmakefile.

Comment (ams) [reply GNUmakefile]: How hard would it be to make it work on BSD make and GNU make?

File: GNUmakefile [hunk 15]
```diff
@@ -0,0 +1,71 @@
...
+
+SHELL = /bin/sh
+PREFIX ?= /usr/local
+
+CC ?= cc
```
Comment (ams) [inline GNUmakefile]: CC is always set by make.

File: GNUmakefile (hunk 8 above)
Comment (johnsonjh) [reply GNUmakefile]: Impossible - they use completely different syntax for control flow.

**Comment by ams** [comment]
Maybe we should get this in as is, since it contains lots of good changes.  And any other fixes can be done in a different PR?

**Comment by johnsonjh** [comment]
> Maybe we should get this in as is, since it contains lots of good changes. And any other fixes can be done in a different PR?

It will probably be easier to not mess with the whitespace here (rather than undo those changes later).  Give me a few days to get around to it.  Sorry, I forgot about it awhile before!

**Comment by larsbrinkhoff** [comment]
> Maybe we should get this in as is, since it contains lots of good changes. And any other fixes can be done in a different PR?

I think this is the wrong approach.  "Fix later" often becomes "fix never".  A pull request should be cleaned up before merging.  If it seems to take too long, or is too much work, maybe open a new pull request with only the good commits.

File: GNUmakefile (hunk 8 above)
Comment (larsbrinkhoff) [reply GNUmakefile]: The reason is that I'm generally wary of cosmetic changes.  In my opinion, they are often not worth it.

**Comment by johnsonjh** [comment]
I'll be able to work on it this weekend.

**Comment by ams** [comment]
> > Maybe we should get this in as is, since it contains lots of good changes. And any other fixes can be done in a different PR?
> 
> I think this is the wrong approach. "Fix later" often becomes "fix never". A pull request should be cleaned up before merging. If it seems to take too long, or is too much work, maybe open a new pull request with only the good commits.

There is also the other side of the coin, that continuously fixing minor points here and there it will never get merged because the person doing the work runs out of steam.  Many of the changes here are good ones, some are more of minute importance, and some are just why.  Splitting it up sounds like a good idea.

File: chaos.c (hunk 4 above)
Comment (johnsonjh) [reply chaos.c]: Done.

File: supdup.c (hunk 11 above)
Comment (johnsonjh) [reply supdup.c]: Will do in another PR

File: README.md (hunk 14 above)
Comment (johnsonjh) [reply README.md]: Done.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Review by larsbrinkhoff — APPROVED** [review]
Approved.
